apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4QraEJ/nCBNqRHaSGnI6PQ==,iv:41L9mvuPjqPUY3qTVjmvhistKLKrstsLPWNHG13I5mQ=,tag:c/xPCj9RGNWFa0nBugO1+Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:e2RoIftfj76aZjy+3E5LF2Z37HX7OVfNhOHyymlsB2+88XNKdQ==,iv:rXsz6UbbvAIPK9Z214/kbXet3cn11lBGw3OwgFTQPeo=,tag:YXDh41ujyhB0Ezj+taLvRA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:p20bFAzO56XoEwBZD25lyG98qJE=,iv:IRAZOmzZfemgcfZApedwH3jQAUdSwkExqX4uOFVazD8=,tag:HwHbi78b+Rvf9Zv0cXgtZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xfngu8m7w7epw797sdnjc746ysuksxevnucr9t4alq82hgzxdagq4u2y4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y1ltQzFTV0o0aVBTS1Fp
            UkdpVE1GOFhRV2FxQytJYjBxUGk4M2dkdnpnCjJQbm9Oazh5UGxCNDdtdlhKWndi
            THhCdnEzRUd3em5DZkk0T3NpRXZaZzQKLS0tIHVWdzlaM0xIZFZaM1hnbTV6SFVR
            NGZrOVBxNUNmUTJvSUhsSjUwVEg4N0kKyj7KiLD4wqUhxTOdm5L+NcbCpzgbQElS
            mNSheSdCo/E+sYf/fAetaU05RlnToGpCCeiSySs+gJkjEPu00EGJZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T02:18:17Z"
    mac: ENC[AES256_GCM,data:C9swLknHWmzPI9SmK4Tlcub+YY9hZksL2QD6GN36Wt5oPL/J8EnyrHFrZ8ZEmr1u9ULtmhtrNM4Yrp2S0IPNjuqgCX6JeyzxEnDFdnnE4FXrP8uxFTFwhDNDqgFKjcA9PTtW+FRJ2qICbNUKihfFOU7RXYhlwEh7Ss4kFdQzS+Q=,iv:kBSG9epa0ZCp8O6WKmmhyfsbpAcoYV2d0c0NRPszKu8=,tag:+5NuCV9EjLlRqO3ktaMeug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
