---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./intel-gpu-plugin/ks.yaml
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
