---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-config
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.0.8.240:3260
    iqn: iqn.2000-01.com.synology:diskstation.Target-1.01bf470ad83
    lun: 1
    chapAuthSession: false
    fsType: ext4
    readOnly: false
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: readarr-config
