---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: esphome
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 250m
        memory: 0.5Gi
      limits:
        cpu: 2000m
        memory: 1Gi
    image:
      repository: esphome/esphome
      tag: "2022.12.3@sha256:653a69520c4417d131f6231146c6e1fd7642405584bdf6badd9821b5664bcc82"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: esphome-tls
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config
