---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/owncloud/ocis-charts
  ref:
    tag: v0.2.0
