kind: ENC[AES256_GCM,data:CORrwb62,iv:vC62i7Y+KwkN6So8GzBBSYGUtKhSSOEU8i3JZLNcL40=,tag:iY5oyTgXm5HebYV8zaE4PQ==,type:str]
ansible_user: ENC[AES256_GCM,data:xIKWYI1whg==,iv:3ESOYVwFi/iWz+WSSApJbpQSWkuSX/AprPwY3PE7rEg=,tag:JrNm13J4fVYEYlCK0e5f4g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:H7ihg8WWLIo=,iv:hzs3v5UWibD6HqPkFjtGLb0f9sTZRxYjC2aacvwqlu0=,tag:CQ0CSt41P+iSvv0zFGk8bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xfngu8m7w7epw797sdnjc746ysuksxevnucr9t4alq82hgzxdagq4u2y4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaGMySzFZd2hyYzBCRU92
            SThaTjFnY00zSXVDRWUxelpTWmdXcWcrWWlJCkQxMWkwd3A2UUN6aVc0Q0VVenRw
            c0YzRzdsT2tpYTdKc05LL0tsbXB3Q1EKLS0tIDRxS1k2UUY4eitJSDRHUEZZc2lU
            RllUTXlRK0lyQk1ETTVDTDBOUDIzbTQKV7vJdU9CoU+CDut2R19HUVfUdwdx8blx
            LKtwHuh3dyz4tILfnp6yMkL5DfWkA/VdaVgCao5KeDlglrujnHshDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T21:20:00Z"
    mac: ENC[AES256_GCM,data:Y1duf9zhhLmvxJKbJCo6pA+DfP9RwdjemtEDjMmeQz8v2BMKqBRCz7OgGRCWzmwFSbCo9lOxw3kjwOBiIDkY6a8xCaZteiBz5eXFcYGqGdSHua4FZfDtsZJt7UjJ7efn9gt7ERPSG6Mlg4lMf4Gzg3UItHxky6eD4U5eqRdl5yo=,iv:o3ENeNLAGScEZn9QBCWFf6ZEciaACncQqD/10rzMgAw=,tag:AuQ5b5WRH+RvXpX6XJ91yw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
