---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtl433
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # https://github.com/hertzg/rtl_433_docker
    image:
      repository: ghcr.io/hertzg/rtl_433_docker
      tag: "master-alpine3.12@sha256:083fff7f0678dd2bacc1af4b7b1e57cbbb850c01c0d88efd21b91786108d2930"
      pullPolicy: IfNotPresent
    args:
      # - '-h'
      - '-f 915000000'
      - '-s 1024k'
      - '-Mtime:unix:usec:utc'
      - '-Mbits'
      - '-Mlevel'
      - '-Mprotocol'
      - '-Mstats:2:300'
      - '-Fmqtt://emqx.default.svc.cluster.local:1883,user=admin,pass=admin,retain=1'
    service:
      main:
        enabled: false
    nodeSelector:
      feature.node.kubernetes.io/usb-ff_0bda_2838.present: 'true' # Require the rtl-sdr
    securityContext:
      privileged: true
