---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./jellyfin/ks.yaml
  - ./lidarr/ks.yaml
  - ./mariadb/ks.yaml
  - ./nzbget/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./ocis/ks.yaml
