---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./emqx/ks.yaml
  - ./esphome/ks.yaml
  - ./hajimari/ks.yaml
  - ./home-assistant/ks.yaml
  - ./jellyfin/ks.yaml
  - ./lidarr/ks.yaml
  - ./nzbget/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./rtl433/ks.yaml
  - ./sonarr/ks.yaml
