---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./emqx/ks.yaml
  - ./esphome/ks.yaml
  - ./hajimari/ks.yaml
  - ./jellyfin/ks.yaml
  - ./rtl433/ks.yaml
