apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:+PfGlkACiaRlxGQ24s7MN1wkthnp2kJdvC4s62zuI5Yn98eTYIYfKrYj4nkRPwdzzx2AjoJRGqQ002b2,iv:JpL0fd2CQBhHS+CummAPJTupzRNgFcDVeY8CTd4ZyF8=,tag:AT4Etm4ybex/ulkIWza+Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xfngu8m7w7epw797sdnjc746ysuksxevnucr9t4alq82hgzxdagq4u2y4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bzZCMUpvSWNwYnA2WFBR
            SG1rR2I1eDhOaTlqV0VLTHZPdlVWVmxxOVdRClorREhzTlZPQ2YxaWhLcDNKVXdw
            YzY0SU1UN2JaZ2d0T09raDVJd3JuZG8KLS0tIHZRSVQ5aFhBek9oVHhvRlpxR0th
            ZStoMEpnT2UxaFFybnNocUtIU1lzdGsKjhxl9kGGie+YIqeYmCx5PVpvcQcgBgYL
            2X93R5feI3Dp2NgWqfjMly56Nuj7IORJOPPhLRBP18otrxFEHswUmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T21:20:00Z"
    mac: ENC[AES256_GCM,data:a9uKmNmCdWYqOumxCEwTA6NeDPFs9VoE2lpRC+eOXe3N9ONuCI+qcintKnfFgvEuvIH2eGn2R0oxDwxq5x0vRrTSHUhVmD1YXt8b7jnDKJcJx8+wYJMGtJ/e/mtdKacYeEwY4rdyVmbg//Y7vJ7b4QfDeGm7I44js0yRFtodV1M=,iv:Y9iHYGMc9/2+5K4dGdp0BunNCBZ8hclgxx3ropjm1kc=,tag:PXJ0YUvtU2Z0YDpJySl0cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
