apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:5SLjD3V888g3+YE2V2z6euYwhA0ULm+nqZQY7X2TKUNXhEKbrXyCcHFgwew5RXneH08Sw8l6tQS/+era,iv:3aW7p0oQ86W4b3S9GzmtzkBmlcbz55KSy8W4NjPAcv0=,tag:iqQ+S5w5p0u6+TOAB3L5Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xfngu8m7w7epw797sdnjc746ysuksxevnucr9t4alq82hgzxdagq4u2y4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRFc1R1I2M2VOdkJxZEZX
            UHlySGF6UjF5SVl3OThFbE5PSlJVTEQ1cUFBClozOHIvUFlSRXRTSEh4U0xBWEpn
            bnVIOUM4SlVoeVNRQVRiSGhVZmRFTFEKLS0tIEI5TW9ybGtQc3RObE5zbkRxczIv
            WTRJYVJRWTZtYks4WERjM2hoYy8vVlEKoRW8oXzeaWfOW4bWYmMMU+GbXQ9Q3RU3
            bii1Jp9Kq+I9whP4MwmXB/WTKF3GDYg+dU+nh6glg8FbjPH8baBTmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T02:18:18Z"
    mac: ENC[AES256_GCM,data:mkUO3KXLe5M2zQJJiLZZOL3vRrDRFN3a9g3z5NtjOA0mbKUdGbyQVSKIYSYON4lo3C4JgyebR8RJ/Twynz5spoEMZYdbmav0icIDrrpkTDPlaq+Piyn0cSe0QLZs6IY9d1f6dR2oZuAUje6u4ib28Zt9fQZiDeqgBWmI4UDRoAM=,iv:jzWfKk57PUNdXVXpoblDFhxu6pKVBRF2hANYOe3339M=,tag:SjnvlNQmucBG0eLdroNibg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
