---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.0.8.50"
  METALLB_LB_RANGE: "10.0.8.20-10.0.8.49"
  METALLB_K8S_GATEWAY_ADDR: "10.0.8.30"
  METALLB_INGRESS_ADDR: "10.0.8.31"
