apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8YxeIU2onQC+SFHmcczq,iv:V9b5UMc9xuSQ0aErrXOKXjVw1Xk4I+R+UPMqukd1i+Y=,tag:v7uz0Ddvrkanj2rTF/lW5w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZvZ/rqE1Mjrjy0t6BHnTxg==,iv:4vXquzeatpB3eNteieX0vsuhcTBldYd5GFO5XlT68kE=,tag:rWLCuTT6JMxP7va2nbKCMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xfngu8m7w7epw797sdnjc746ysuksxevnucr9t4alq82hgzxdagq4u2y4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdjZUMVQxQ1JOWFdzWnhS
            TTgxUkc2VUpxN2Q3eUJhZ1JKK0JVMThFUlF3CjZNQUU4OTZsWVh1cUU1bDVkQ25M
            MHJsNGtScVJSVmxQdmNBZjJGTUtIcGsKLS0tIE9kWnhlbVZyZTVYMXVCZHZHbHV4
            QXUxSjhZQ1h6Qnp6WFN6Q1Nld2ZNOG8KU0bX949RhwBVrl4eFUJCCELuwU1YY7XC
            q+JJj188z0PJ3v8988PRDlhyrmDyuOzJ1rmyXRIX+5rs6IK0SpmgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T02:18:17Z"
    mac: ENC[AES256_GCM,data:sK3eLpCrV34QW9idNTAaoB111h7/aB6eTFwZKsX6sXmY8sBSZ9rsa0kyha27gI3jJBGTwUSVTtEmrSOR6YYYR7SITOCEr3IwoImVJLEkmPejB7A9eJR+ILv1FU4EuoZnP/PfFzaonmoMdN86KTpRrDNibXf/8IaDJkwFtfkMx14=,iv:2CA7Dok05Ey/wKBVy6S2NZ+g+tF4TcpUFgYllgKVMRk=,tag:wj9e7PhgojTpC9mcdR4l9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
