---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app firefly
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: firefly-iii-stack
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    firefly-db:
      # if you set this to false it will not be installed
      enabled: false

    # https://github.com/firefly-iii/kubernetes/blob/main/charts/firefly-iii/values.yaml
    firefly-iii:
      # -- Set to false to not deploy Firefly III
      enabled: true
      image:
        repository: "fireflyiii/core"
        pullPolicy: IfNotPresent
        tag: version-5.7.16
      persistence:
        # -- If you set this to false, uploaded attachments are not stored persistently and will be lost with every restart of the pod
        enabled: true
        type: pvc
        existingClaim: firefly-config
      config:
        env:
          DB_CONNECTION: mysql
          DB_HOST: mariadb.default.svc.cluster.local
          DB_PORT: 3306
          DB_DATABASE: "${FIREFLY_MARIADB_USERNAME}"
          DB_USERNAME: "${FIREFLY_MARIADB_USERNAME}"
          DB_PASSWORD: "${FIREFLY_MARIADB_PASSWORD}"
          APP_KEY: "${FIREFLY_KEY}"
          DEFAULT_LANGUAGE: "en_US"
          DEFAULT_LOCALE: "equal"
          TZ: "America/Chicago"
          TRUSTED_PROXIES: "**"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - &host "firefly.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: firefly-ingress-cert
      resources:
        requests:
          cpu: 250m
          memory: 0.5Gi
        limits:
          cpu: 2000m
          memory: 1Gi
    importer:
      # -- Set to false to not deploy the importer
      enabled: false
